# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='user',
            field=models.CharField(default='aaa', max_length=64, verbose_name='会员名称'),
            preserve_default=False,
        ),
    ]
