# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rec_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='号码'),
        ),
    ]
