# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='money',
            field=models.IntegerField(default=0, verbose_name='奖金'),
        ),
    ]
